### ISSUE TITLE
no version option 

### ISSUE THREAD

**Issue by johanpeters** [R2H-BV/moduleversion#1]
After installing v2.0.3 on joomla 4.2.8
i dont have a version tab / setting when editing front or administrator modules ..
plugin is enabled and 10 versions ar set.

**Comment by ricardo1709** [comment]
I have tested it on version 2.0.4 with joomla 5.0.0 rc2

It does show any module before installing and enabling the plugin with version button/tab. The button/tab will be visable when the module is saved.

For the button/tab in the frontend. It not a bug that you dont have one in the frontend. This plugin in only works in the administrator.
