### ISSUE TITLE
all hyperlinks are getting stripped as soon as you restore from the Versions button

### ISSUE THREAD

**Issue by woluweb** [R2H-BV/moduleversion#2]
Hi Rick & co,

I had already faced that issue but I had realized initially that it was coming from this plugin :)
In Joomla's backend, I have typically an HTML Module to add my own notes about the website, with plenty of URLs.
And actually, as soon as you restore a previous version with the Versions button, all links are stripped 🤔 
Today again I had that strange issue... so I made a proper test... and indeed I do confirm the issue with the current version 2.0.3

See you very soon at #jd23nl 😃

**Comment by ricardo1709** [comment]
This bug has been fixed in #5 and has been published in version 2.0.4.

Thanks for the report.
